name: 💡Feature request
description: Suggest an improvement to the project
title: "[FEATURE]"
labels: [enhancement]
body:
  - type: textarea
    id: area
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: Provide a clear and concise description of what the problem is e.g., I am always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you would like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the reason you believe this solution is necessary
      description: Explain why we should add this feature. Provide use cases to illustrate its benefits.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context like links or references about the problem here. Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
