name: Lint Markdown Links
run-name: ${{github.event.pull_request.title}}
on: [ pull_request ]
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@d53a906aa6b22b8979d33bc86170567e619495ec
        with:
          use-verbose-mode: 'no'
          config-file: '.mlc.config.json'
          folder-path: '.'
          max-depth: -1
