name: Lint Markdown Links
run-name: ${{github.event.pull_request.title}}
on: [ pull_request ]
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@3c3b66f1f7d0900e37b71eca45b63ea9eedfce31
        with:
          use-verbose-mode: 'no'
          config-file: '.mlc.config.json'
          folder-path: '.'
          max-depth: -1
