name: push-actions
on:
  push:
    branches: ["main", "release-*"]

jobs:
  gh-actions-integration-test:
    runs-on: ubuntu-latest
    environment: secrets

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: ./.github/actions/create-sap-btp-kyma
        id: create-btp-resources
        with:
          btp_subaccount_name: tf-actions-${{ github.sha }}-${{ github.run_attempt }}
          btp_backend_url: '${{ vars.BTP_BACKEND_URL }}'
          btp_user: '${{ vars.BTP_BOT_USER }}'
          btp_password: '${{ secrets.BTP_BOT_PASSWORD }}'
          btp_global_account: '${{ vars.BTP_GLOBAL_ACCOUNT }}'
          btp_idp_tenant: '${{ vars.BTP_CUSTOM_IAS_TENANT }}'
          btp_subaccount_region: '${{ vars.BTP_SUBACCOUNT_REGION }}'
          btp_kyma_region: '${{ vars.BTP_KYMA_REGION }}'
          btp_kyma_plan: '${{ vars.BTP_KYMA_PLAN }}'
      - name: kyma environment sanity check
        run: |
          kubectl get nodes
      - uses: ./.github/actions/force-delete-sap-btp-subaccount
        if: always()
        with:
          btp_subaccount_id: ${{ steps.create-btp-resources.outputs.subaccount_id }}
          btp_backend_url: ${{ vars.BTP_BACKEND_URL}}
          btp_user: ${{ vars.BTP_BOT_USER}}
          btp_password: ${{ secrets.BTP_BOT_PASSWORD}}
          btp_global_account: ${{ vars.BTP_GLOBAL_ACCOUNT }}
          btp_idp_tenant: ${{ vars.BTP_CUSTOM_IAS_TENANT }}
