name: push-e2e-test
on:
  push:
    branches: ["main", "release-*"]

jobs:
  btp-integration-tests:
    runs-on: ubuntu-latest
    environment: secrets
    
    steps:
      - uses: actions/checkout@v7
      - name: compute github commit sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_wrapper: false
      - name: Create kyma runtime on btp
        working-directory: tests/btp-e2e-test
        run: |
          terraform init
          terraform apply -auto-approve

          kubectl auth can-i --kubeconfig=kubeconfig.yaml update kymas
          
          APISERVER_URL=$(terraform output --raw apiserver_url)
          TOKEN=$(cat kubeconfig.yaml | yq .users.0.user.token)
          kubectl auth can-i update kymas \
            --token=$TOKEN \
            --server=$APISERVER_URL \
            --certificate-authority=CA.crt

          terraform destroy -auto-approve
        env:
          TF_VAR_BTP_NEW_SUBACCOUNT_NAME: tf-kyma-module-test-${{ steps.vars.outputs.sha_short }}-${{ github.run_attempt }}
          TF_VAR_BTP_NEW_SUBACCOUNT_REGION: ${{ vars.BTP_SUBACCOUNT_REGION }}
          TF_VAR_BTP_GLOBAL_ACCOUNT: ${{ vars.BTP_GLOBAL_ACCOUNT }}
          TF_VAR_BTP_BOT_USER: ${{ vars.BTP_BOT_USER }}
          TF_VAR_BTP_BOT_PASSWORD: ${{ secrets.BTP_BOT_PASSWORD }}
          TF_VAR_BTP_KYMA_PLAN: ${{ vars.BTP_KYMA_PLAN }}
          TF_VAR_BTP_KYMA_REGION: ${{ vars.BTP_KYMA_REGION }}
          TF_VAR_BTP_CUSTOM_IAS_TENANT: ${{ vars.BTP_CUSTOM_IAS_TENANT }}
          TF_VAR_BTP_BACKEND_URL: ${{ vars.BTP_BACKEND_URL }}
