name: pull-e2e-test
on:
  push:
    branches: ["main", "release-*"]

jobs:
  btp-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: compute github commit sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Create kyma runtime on btp
        working-directory: examples/kyma-on-btp-new-sa
        run: |
          terraform init
          terraform apply -auto-approve
          terraform destroy -auto-approve
        env:
          TF_VAR_BTP_NEW_SUBACCOUNT_NAME: tf-kyma-module-test-${{ steps.vars.outputs.sha_short }}-${{ github.run_attempt }}
          TF_VAR_BTP_NEW_SUBACCOUNT_REGION: ${{ secrets.sa_region }}
          TF_VAR_BTP_GLOBAL_ACCOUNT: ${{ secrets.global_account }}
          TF_VAR_BTP_BOT_USER: ${{ secrets.username }}
          TF_VAR_BTP_BOT_PASSWORD: ${{ secrets.password }}
          TF_VAR_BTP_KYMA_PLAN: ${{ secrets.kyma_plan }}
          TF_VAR_BTP_KYMA_REGION: ${{ secrets.kyma_region }}
          TF_VAR_BTP_CUSTOM_IAS_TENANT: ${{ secrets.ias_tenant }}
          TF_VAR_BTP_CUSTOM_IAS_DOMAIN: ${{ secrets.ias_domain }}
          TF_VAR_BTP_BACKEND_URL: ${{ secrets.btp_api_url }}
